POST http://localhost:8080/message-board/message
Content-Type: application/json

{
    "title": "关于午餐食堂的反馈",
    "content": "我认为食堂的菜品种类可以再多一些，因为目前的选择有点单一。同时，希望能够增加一些健康饮品的选项，让同学们有更多健康的选择。谢谢大家的努力！",
  "categoryId": 1,
  "tagIdList": [
    2,
    3,
    4
  ]
}


### detail
GET http://localhost:8080/message-board/message/detail/1